# Generated by Django 5.1.7 on 2025-03-21 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_points', models.DecimalField(decimal_places=2, default=1.5, help_text='Pourcentage de la prime nette converti en points', max_digits=5)),
                ('duree_validite_points', models.IntegerField(default=365, help_text='Durée de validité des points en jours')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
            },
        ),
        migrations.CreateModel(
            name='Ambassadeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ambassadeur', models.CharField(max_length=10, unique=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambassadeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ambassadeur',
                'verbose_name_plural': 'Ambassadeurs',
            },
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_police', models.CharField(max_length=50, unique=True)),
                ('prime_nette', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(default='payé', max_length=50)),
                ('source_systeme', models.CharField(choices=[('ORASS', 'ORASS'), ('HELIOS', 'HELIOS')], max_length=50)),
                ('date_paiement', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ambassadeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polices', to='ambassadeurs.ambassadeur')),
            ],
            options={
                'verbose_name': 'Police',
                'verbose_name_plural': 'Polices',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ambassadeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_gagnes', to='ambassadeurs.ambassadeur')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='ambassadeurs.exercice')),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='ambassadeurs.police')),
            ],
            options={
                'verbose_name': 'Points',
                'verbose_name_plural': 'Points',
            },
        ),
    ]
