# Generated by Django 5.1.7 on 2025-04-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadeurs', '0002_alter_ambassadeur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='type_police',
            field=models.CharField(blank=True, help_text='Type spécifique de police (ex: Individuel accident, Automobile)', max_length=100, null=True),
        ),
    ]
