# Generated by Django 5.1.7 on 2025-03-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambassadeurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieRecompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie de récompense',
                'verbose_name_plural': 'Catégories de récompenses',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Recompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cout_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recompenses/')),
                ('quantite_disponible', models.IntegerField(default=-1)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompenses', to='rewards.categorierecompense')),
            ],
            options={
                'verbose_name': 'Récompense',
                'verbose_name_plural': 'Récompenses',
                'ordering': ['cout_points', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Echange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_utilises', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ambassadeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='ambassadeurs.ambassadeur')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='ambassadeurs.exercice')),
                ('recompense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='rewards.recompense')),
            ],
            options={
                'verbose_name': 'Échange',
                'verbose_name_plural': 'Échanges',
                'ordering': ['-date_creation'],
            },
        ),
    ]
